### ISSUE TITLE
Are documentations going to be included later on for the guide on deep linking?

### ISSUE THREAD

**Issue by levi956** [Mastersam07/deepa#3]
Not exactly an issue, but the repository says "guide for a deep link in flutter", but the texts on the readme.md files aren't directed to a page for learning reference.

**Comment by Mastersam07** [comment]
Hi @levi956 

I am working on a corresponding article which should be out sometime today. Currently, the readme just tracks all I intend to do on the repo and article. Once done, I will update the readme accordingly and this issue.

To answer your question, yes, documentation will be included.

**Comment by Mastersam07** [comment]
@levi956 

Documentation is available [here](https://medium.com/@codefarmer/deep-linking-in-flutter-boost-user-experience-in-apps-29dd25842757). Writing a readme to show the guide promises to be a hassle but the medium article should do it.
